name: Python SAST with Bandit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r . -f json -o bandit-report.json --exit-zero

    - name: Display Bandit Report
      run: cat bandit-report.json

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit-report.json
